import { Exercise, Language, ReadyWorkout } from './types';

const DEFAULT_VIDEO_URL = 'https://www.canva.com/design/DAG7I21NAys/Ky9YIR8o0ItCpV1USwDXng/watch?utm_content=DAG7I21NAys&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=h4262beef57';

export const TRANSLATIONS: Record<string, Record<Language, string>> = {
  guideTitle: { pt: "Guia de", en: "Guide to" },
  guideSubtitle: { pt: "Fortalecimento", en: "Knee Strengthening" },
  guideContext: { pt: "de Joelho", en: "" },
  homeDesc: { pt: "Seu manual de bolso para treinar com segurança.", en: "Your pocket manual for safe training." },
  startBtn: { pt: "INICIAR GUIA", en: "START GUIDE" },
  resumeTitle: { pt: "Treino em Andamento", en: "Workout in Progress" },
  resumeDesc: { pt: "Deseja continuar o último treino que você estava fazendo?", en: "Do you want to resume your last workout?" },
  no: { pt: "NÃO", en: "NO" },
  yes: { pt: "SIM", en: "YES" },
  forWhoTitle: { pt: "Para quem é?", en: "Who is this for?" },
  forWhoDesc: { pt: "Para você que treina musculação, quer evoluir cargas, mas sente insegurança ou desconforto no joelho durante a execução.", en: "For you who lift weights, want to increase loads, but feel insecurity or knee discomfort during execution." },
  problemTitle: { pt: "O Problema ⚠️", en: "The Problem ⚠️" },
  problemDesc: { pt: "Execuções com ajustes errados geram sobrecarga articular invisível. Com o tempo, isso vira dor crônica e lesão.", en: "Executions with wrong adjustments generate invisible joint overload. Over time, this becomes chronic pain and injury." },
  solutionTitle: { pt: "A Solução ✅", en: "The Solution ✅" },
  solutionDesc: { pt: "Um comparativo rápido: Sua Ficha vs. Execução Correta. Ajuste a máquina, posicione o corpo e treine sem dor.", en: "A quick comparison: Your Routine vs. Correct Execution. Adjust the machine, position your body, and train without pain." },
  accessMenu: { pt: "Toque abaixo para acessar", en: "Tap below to access" },
  accessBtn: { pt: "Acessar Menu", en: "Access Menu" },
  menuTitle: { pt: "Menu de Treinamento", en: "Training Menu" },
  recWorkoutTitle: { pt: "Treinos Prontos", en: "Ready Workouts" },
  recWorkoutSub: { pt: "Sugestões do Guia", en: "Guide Suggestions" },
  adaptTitle: { pt: "Adaptação da sua FICHA", en: "Adapt your ROUTINE" },
  adaptSub: { pt: "Ajuste seu treino atual", en: "Adjust your current workout" },
  principalHeader: { pt: "Principal", en: "Main Menu" },
  understandTitle: { pt: "Entenda a Adaptação", en: "Understand the Adaptation" },
  adaptCardTitle: { pt: "Adaptação da sua Ficha", en: "Adapting Your Routine" },
  adaptText1: { pt: "Aqui você irá selecionar os exercícios que estão na ficha de treino que sua academia ou professor montou.", en: "Here you will select the exercises that are in the workout routine your gym or trainer created." },
  adaptText2: { pt: "Nós faremos os ajustes técnicos necessários para fortalecer sua musculatura e preservar seus joelhos durante a execução.", en: "We will make the necessary technical adjustments to strengthen your muscles and preserve your knees during execution." },
  proceed: { pt: "PROSSEGUIR", en: "PROCEED" },
  setupTitle: { pt: "Montar Treino", en: "Build Workout" },
  howMany: { pt: "Quantos exercícios para membros inferiores?", en: "How many lower body exercises?" },
  selectCount: { pt: "Selecione quantos exercícios de MEMBROS INFERIORES da sua ficha você fará hoje?", en: "Select how many LOWER BODY exercises from your routine you will do today?" },
  chooseExercises: { pt: "Escolher Exercícios", en: "Choose Exercises" },
  chooseTitle: { pt: "Escolha Exercícios", en: "Choose Exercises" },
  searchPlaceholder: { pt: "Buscar exercício...", en: "Search exercise..." },
  notFound: { pt: "Nenhum exercício encontrado.", en: "No exercises found." },
  selected: { pt: "Selecionados", en: "Selected" },
  startWorkout: { pt: "Iniciar Treino", en: "Start Workout" },
  activeTitle: { pt: "Seu Treino", en: "Your Workout" },
  noActive: { pt: "Nenhum treino ativo encontrado.", en: "No active workout found." },
  createWorkout: { pt: "Criar Treino", en: "Create Workout" },
  quickFixLabel: { pt: "Correção Rápida", en: "Quick Fix" },
  stepsLabel: { pt: "Passo a Passo", en: "Step by Step" },
  detailsBtn: { pt: "Ver Detalhes Completos", en: "View Full Details" },
  finishWorkout: { pt: "Finalizar Treino", en: "Finish Workout" },
  recScreenTitle: { pt: "Treinos Prontos", en: "Ready Workouts" },
  sugTitle: { pt: "Sugestões de Treino", en: "Training Suggestions" },
  sugDesc: { pt: "Selecione um dos protocolos abaixo para iniciar seu fortalecimento.", en: "Select one of the protocols below to start strengthening." },
  workout2x: { pt: "TREINO 2x SEMANA", en: "2x WEEK WORKOUT" },
  workout3x: { pt: "TREINO 3x SEMANA", en: "3x WEEK WORKOUT" },
  important: { pt: "IMPORTANTE", en: "IMPORTANT" },
  impText1: { pt: "Use as sugestões de treino deste guia como apoio inicial. Siga o modelo de execução indicado aqui até", en: "Use the workout suggestions in this guide as initial support. Follow the execution model indicated here until you" },
  feelSafe: { pt: "SENTIR SEGURANÇA", en: "FEEL SAFE" },
  impText2: { pt: ", para continuar com o treino prescrito pela academia ou pelo seu profissional.", en: ", to continue with the workout prescribed by your gym or professional." },
  impText3: { pt: "Um dos pontos mais importantes para manter seus joelhos saudáveis é estar 100% atento ao ângulo de execução em cada movimento.", en: "One of the most important points to keep your knees healthy is to be 100% attentive to the execution angle in every movement." },
  weightInstruction: { 
    pt: "Registre suas cargas de costume no treino. Tenha atenção ao número de repetições: cargas para 8 repetições tendem a ser mais elevadas, já para 15 são reduzidas. Se você costuma treinar com menos repetições, sugerimos reduzir de 10 a 20% da carga habitual para realizar as 15 repetições sugeridas.", 
    en: "Register your usual weights. Pay attention to reps: loads for 8 reps tend to be higher than for 15. If you usually train with fewer reps, we suggest reducing your load by 10 to 20% for these 15-rep protocols." 
  },
  setsRecommended: { pt: "Recomendação: 15 repetições com intensidade sem dor.", en: "Recommendation: 15 reps with intensity but no pain." },
  serie: { pt: "Série", en: "Set" },
  repeticao: { pt: "Repetição", en: "Reps" },
  carga: { pt: "Sua Carga", en: "Your Weight" },
  intervalo: { pt: "Intervalo", en: "Rest" },
  intervalValue: { pt: "45 seg", en: "45 sec" },
  timerTitle: { pt: "Cronômetro", en: "Timer" },
  timerHint: { pt: "Clique p/ Iniciar/Pausar • Segure p/ Zerar", en: "Click to Start/Pause • Hold to Reset" },
  congratsTitle: { pt: "Treino Concluído?", en: "Workout Finished?" },
  congratsDesc: { pt: "A consistência e a técnica correta são os segredos para joelhos de aço. Bom descanso!", en: "Consistency and correct technique are the secrets to steel knees. Rest well!" },
  backHome: { pt: "Voltar ao Início", en: "Back to Home" },
};

export const EXERCISES: Exercise[] = [
  {
    id: 'agachamento-parcial',
    name: { pt: 'Agachamento Parcial', en: 'Partial Squat' },
    iconName: 'ArrowDownUp',
    category: 'basic',
    shortDescription: { pt: 'Ângulo de proteção.', en: 'Protection angle.' },
    objective: { pt: 'Fortalecimento seguro sem dor.', en: 'Safe strength without pain.' },
    steps: { pt: ['Pés largura ombros.', 'Desça até ângulo confortável.', 'Não estenda joelho total no topo.', 'Mantenha tensão.'], en: ['Feet shoulder width.', 'Lower to comfy angle.', 'No full knee lock at top.', 'Maintain tension.'] },
    quickFix: { pt: 'Ângulo de proteção é não extender o joelho por completo.', en: 'Protection angle means not extending the knee fully.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'single-legs',
    name: { pt: 'Single Legs', en: 'Single Legs' },
    iconName: 'Activity',
    category: 'stabilization',
    shortDescription: { pt: 'Unilateral e equilíbrio.', en: 'Unilateral and balance.' },
    objective: { pt: 'Estabilização profunda.', en: 'Deep stabilization.' },
    steps: { pt: ['Apoie em uma perna.', 'Mantenha joelho levemente flexionado.', 'Equilibre e controle.', 'Sinta estabilidade.'], en: ['Stand on one leg.', 'Keep knee slightly bent.', 'Balance and control.', 'Feel stability.'] },
    quickFix: { pt: 'Mantenha o quadril nivelado.', en: 'Keep hips level.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'elevacao-pelvica',
    name: { pt: 'Elevação Pélvica', en: 'Hip Thrust' },
    iconName: 'Layers',
    category: 'basic',
    shortDescription: { pt: 'Potência de glúteo.', en: 'Glute power.' },
    objective: { pt: 'Máxima ativação do glúteo.', en: 'Max glute activation.' },
    steps: { pt: ['Escápulas no banco.', 'Pés firmes no chão.', 'Suba contraindo glúteo.', 'Queixo perto do peito.'], en: ['Shoulder blades on bench.', 'Feet firm on floor.', 'Lift squeezing glutes.', 'Chin tucked.'] },
    quickFix: { pt: 'Contraia o abdômen para proteger a lombar.', en: 'Tighten abs to protect back.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'abducao-elastico-fa',
    name: { pt: 'Abdução com Elástico (Frente/Atrás)', en: 'Band Abduction (Fwd/Back)' },
    iconName: 'MoveHorizontal',
    category: 'stabilization',
    shortDescription: { pt: 'Estabilidade glútea.', en: 'Glute stability.' },
    objective: { pt: 'Ativar glúteo médio em vários ângulos.', en: 'Activate glute medius at various angles.' },
    steps: { pt: ['Band nos tornozelos.', 'Abra para o lado.', 'Movimente levemente frente e trás.', 'Mantenha tensão constante.'], en: ['Band on ankles.', 'Open to side.', 'Move slightly fwd and back.', 'Maintain constant tension.'] },
    quickFix: { pt: 'Mantenha o tronco ereto.', en: 'Keep torso upright.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'leg-press-parcial',
    name: { pt: 'Leg Press Parcial', en: 'Partial Leg Press' },
    iconName: 'ArrowDownUp',
    category: 'basic',
    shortDescription: { pt: 'Proteção no Leg Press.', en: 'Protection in Leg Press.' },
    objective: { pt: 'Carga segura sem estresse articular.', en: 'Safe load without joint stress.' },
    steps: { pt: ['Posicione-se no Leg.', 'Empurre sem esticar tudo.', 'Desça até ângulo de conforto.', 'Mantenha o pé firme.'], en: ['Position on Leg.', 'Push without full lock.', 'Lower to comfort angle.', 'Keep feet firm.'] },
    quickFix: { pt: 'Ângulo de proteção é não extender o joelho por completo.', en: 'Protection angle means not extending the knee fully.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'sumo-parcial',
    name: { pt: 'Sumô Parcial', en: 'Partial Sumo' },
    iconName: 'ArrowDownUp',
    category: 'basic',
    shortDescription: { pt: 'Adutores protegidos.', en: 'Protected adductors.' },
    objective: { pt: 'Foco em parte interna com segurança.', en: 'Focus on inner thigh with safety.' },
    steps: { pt: ['Base sumô (pés para fora).', 'Desça controlado.', 'Suba mantendo joelho flexionado.', 'Sinta os adutores.'], en: ['Sumo stance (toes out).', 'Lower controlled.', 'Rise keeping knee bent.', 'Feel adductors.'] },
    quickFix: { pt: 'Não estenda o joelho por completo no topo.', en: 'Do not fully extend the knee at the top.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'agachamento-halteres',
    name: { pt: 'Agachamento Halteres', en: 'Dumbbell Squat' },
    iconName: 'ArrowDownUp',
    category: 'basic',
    shortDescription: { pt: 'Segurança na execução.', en: 'Safe execution.' },
    objective: { pt: 'Aprender movimento sem barra.', en: 'Learn movement without bar.' },
    steps: { pt: ['Segure halteres ao lado.', 'Peito aberto.', 'Agache sentando para trás.', 'Empurre chão com calcanhar.'], en: ['Hold dumbbells at sides.', 'Chest open.', 'Squat sitting back.', 'Push floor with heels.'] },
    quickFix: { pt: 'Mantenha o calcanhar firme no chão.', en: 'Keep heels firm on floor.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'passa-peso-ket',
    name: { pt: 'Passa Peso Ket ou Anilha', en: 'Kettlebell/Plate Pass' },
    iconName: 'TrendingUp',
    category: 'stabilization',
    shortDescription: { pt: 'Controle dinâmico.', en: 'Dynamic control.' },
    objective: { pt: 'Estabilidade em movimento.', en: 'Stability in motion.' },
    steps: { pt: ['Base levemente agachada.', 'Passe o peso entre as pernas (em 8).', 'Mantenha joelhos estáveis.', 'Controle o tronco.'], en: ['Slightly squat base.', 'Pass weight between legs (figure 8).', 'Keep knees stable.', 'Control torso.'] },
    quickFix: { pt: 'Joelho não deve "entrar". Force para fora.', en: 'Knee shouldn\'t cave in. Force outward.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'cadeira-adutora',
    name: { pt: 'Cadeira Adutora', en: 'Adductor Machine' },
    iconName: 'MoveHorizontal',
    category: 'basic',
    shortDescription: { pt: 'Parte interna.', en: 'Inner thigh.' },
    objective: { pt: 'Fortalecer adutores.', en: 'Strengthen adductors.' },
    steps: { pt: ['Apoie joelhos.', 'Feche pernas.', 'Segure.', 'Abra.'], en: ['Support knees.', 'Close legs.', 'Hold.', 'Open.'] },
    quickFix: { pt: 'Controle a volta do movimento.', en: 'Control the return motion.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'cadeira-abdutora',
    name: { pt: 'Cadeira Abdutora', en: 'Abductor Machine' },
    iconName: 'MoveHorizontal',
    category: 'basic',
    shortDescription: { pt: 'Lateral do quadril forte.', en: 'Strong lateral hip.' },
    objective: { pt: 'Estabilizar o quadril.', en: 'Stabilize hips.' },
    steps: { pt: ['Costas apoiadas.', 'Afaste as pernas.', 'Segure 1s aberto.', 'Volte devagar.'], en: ['Back supported.', 'Spread legs apart.', 'Hold 1s open.', 'Return slowly.'] },
    quickFix: { pt: 'Mantenha o quadril encostado no banco.', en: 'Keep hips against backrest.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'elevacao-pelvica-iso-uni',
    name: { pt: 'Elevação Pélvica ISO/UNI', en: 'ISO/UNI Hip Thrust' },
    iconName: 'Layers',
    category: 'stabilization',
    shortDescription: { pt: 'Glúteo unilateral com trava.', en: 'Unilateral glute with lock.' },
    objective: { pt: 'Isometria e força unilateral.', en: 'Isometry and unilateral strength.' },
    steps: { pt: ['Posição de elevação pélvica.', 'Tire uma perna.', 'Segure no topo por 2s.', 'Desça e repita.'], en: ['Hip thrust position.', 'Lift one leg.', 'Hold at top for 2s.', 'Lower and repeat.'] },
    quickFix: { pt: 'Pé firme empurrando o chão.', en: 'Foot firm pushing floor.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'stiff-barra',
    name: { pt: 'Stiff com Barra', en: 'Barbell Stiff Leg DL' },
    iconName: 'MoveVertical',
    category: 'basic',
    shortDescription: { pt: 'Alongamento posterior.', en: 'Posterior stretch.' },
    objective: { pt: 'Cadeia posterior.', en: 'Posterior chain.' },
    steps: { pt: ['Joelhos destravados.', 'Desça barra rente.', 'Coluna reta.', 'Suba contraindo.'], en: ['Knees unlocked.', 'Bar close to legs.', 'Straight spine.', 'Lift squeezing.'] },
    quickFix: { pt: 'Mantenha a coluna neutra o tempo todo.', en: 'Keep spine neutral always.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'cadeira-extensora',
    name: { pt: 'Cadeira Extensora', en: 'Leg Extension' },
    iconName: 'Activity',
    category: 'basic',
    shortDescription: { pt: 'Foco total no quadríceps.', en: 'Total focus on quadriceps.' },
    objective: { pt: 'Isolar o músculo da frente da coxa.', en: 'Isolate the front thigh muscle.' },
    steps: { pt: ['Ajuste o encosto.', 'O apoio deve estar acima do tornozelo.', 'Estenda pernas.', 'Controle descida.'], en: ['Adjust backrest.', 'Pad above ankle.', 'Extend legs.', 'Control return.'] },
    quickFix: { pt: 'Não estenda totalmente o joelho para proteger a patela.', en: 'Avoid full extension to protect patella.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'mesa-flexora',
    name: { pt: 'Mesa Flexora', en: 'Lying Leg Curl' },
    iconName: 'Activity',
    category: 'basic',
    shortDescription: { pt: 'Posterior de coxa.', en: 'Hamstrings.' },
    objective: { pt: 'Fortalecer posterior.', en: 'Hamstring strength.' },
    steps: { pt: ['Deite-se.', 'Flexione joelhos.', 'Controle descida.', 'Mantenha quadril fixo.'], en: ['Lie down.', 'Flex knees.', 'Control return.', 'Hips fixed.'] },
    quickFix: { pt: 'Não deixe o quadril levantar da mesa.', en: 'Don\'t let hips lift off pad.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  },
  {
    id: 'elevacao-pelvica-uni-iso',
    name: { pt: 'Elevação Pélvica Uni com Isometria', en: 'Uni Hip Thrust with Isometry' },
    iconName: 'Layers',
    category: 'stabilization',
    shortDescription: { pt: 'Estabilização pélvica máxima.', en: 'Max pelvic stabilization.' },
    objective: { pt: 'Fortalecer glúteo e estabilizar core.', en: 'Strengthen glutes and stabilize core.' },
    steps: { pt: ['Elevação pélvica unilateral.', 'Segure 5s no topo em cada repetição.', 'Controle a descida.', 'Mantenha quadril nivelado.'], en: ['Unilateral hip thrust.', 'Hold 5s at top each rep.', 'Control descent.', 'Keep hips level.'] },
    quickFix: { pt: 'Não deixe o quadril cair para o lado.', en: 'Don\'t let hips dip to the side.' },
    compareTip: { pt: '', en: '' },
    videoUrl: DEFAULT_VIDEO_URL
  }
];

export const PREDEFINED_WORKOUTS: ReadyWorkout[] = [
  {
    id: '2x-a',
    title: { pt: 'TREINO A', en: 'WORKOUT A' },
    frequency: '2x',
    sets: 4,
    exercises: ['agachamento-parcial', 'single-legs', 'elevacao-pelvica', 'abducao-elastico-fa', 'leg-press-parcial', 'sumo-parcial']
  },
  {
    id: '2x-b',
    title: { pt: 'TREINO B', en: 'WORKOUT B' },
    frequency: '2x',
    sets: 4,
    exercises: ['agachamento-halteres', 'passa-peso-ket', 'cadeira-adutora', 'cadeira-abdutora', 'elevacao-pelvica-iso-uni', 'stiff-barra', 'leg-press-parcial']
  },
  {
    id: '3x-a',
    title: { pt: 'TREINO A', en: 'WORKOUT A' },
    frequency: '3x',
    sets: 3,
    exercises: ['agachamento-parcial', 'single-legs', 'elevacao-pelvica', 'cadeira-abdutora', 'leg-press-parcial']
  },
  {
    id: '3x-b',
    title: { pt: 'TREINO B', en: 'WORKOUT B' },
    frequency: '3x',
    sets: 3,
    exercises: ['agachamento-halteres', 'passa-peso-ket', 'cadeira-adutora', 'sumo-parcial', 'stiff-barra', 'leg-press-parcial']
  },
  {
    id: '3x-c',
    title: { pt: 'TREINO C', en: 'WORKOUT C' },
    frequency: '3x',
    sets: 3,
    exercises: ['cadeira-extensora', 'abducao-elastico-fa', 'mesa-flexora', 'stiff-barra', 'elevacao-pelvica-uni-iso']
  }
];